UpdateAgain

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -24,45 +24,47 @@ jobs:
       - name: Run a multi-line script
         run: |
           curl -X POST \
-        -H 'Content-type: application/json' \
-        -H 'auth-token: 668d75fc-304a-4b47-b782-bf0029af4a58' \
-          --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
-          https://api.testrigor.com/api/v1/apps/yufwtfu98Muit8iwb/retest
+            -H 'Content-type: application/json' \
+            -H 'auth-token: 668d75fc-304a-4b47-b782-bf0029af4a58' \
+            --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
+            https://api.testrigor.com/api/v1/apps/yufwtfu98Muit8iwb/retest
+          
           sleep 10
+          
           while true
           do
-          echo " "
-          echo "==================================="
-          echo " Checking TestRigor retest"
-          echo "==================================="
-        response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/yufwtfu98Muit8iwb/status' -H 'auth-token: 668d75fc-304a-4b47-b782-bf0029af4a58' -H 'Accept: application/json')
-          code=$(echo "$response" | grep HTTP |  awk '{print $2}')
-          body=$(echo "$response" | grep status)
-          echo "Status code: " $code
-          echo "Response: " $body
-          case $code in
-            4*|5*)
-              # 400 or 500 errors
-              echo "Error calling API"
-              exit 1
-              ;;
-            200)
-              # 200: successfully finished
-              echo "Test finished successfully"
-              exit 0
-              ;;
-            227|228)
-              # 227: New - 228: In progress
-              echo "Test is not finished yet"
-              ;;
-            230)
-              # 230: Failed
-              echo "Test finished but failed"
-              exit 1
-              ;;
-            *)
-              echo "Unknown status"
-              exit 1
-            esac
-          sleep 10
-        done
+            echo " "
+            echo "==================================="
+            echo " Checking TestRigor retest"
+            echo "==================================="
+            response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/yufwtfu98Muit8iwb/status' -H 'auth-token: 668d75fc-304a-4b47-b782-bf0029af4a58' -H 'Accept: application/json')
+            code=$(echo "$response" | grep HTTP |  awk '{print $2}')
+            body=$(echo "$response" | grep status)
+            echo "Status code: " $code
+            echo "Response: " $body
+            case $code in
+              4*|5*)
+                # 400 or 500 errors
+                echo "Error calling API"
+                exit 1
+                ;;
+              200)
+                # 200: successfully finished
+                echo "Test finished successfully"
+                exit 0
+                ;;
+              227|228)
+                # 227: New - 228: In progress
+                echo "Test is not finished yet"
+                ;;
+              230)
+                # 230: Failed
+                echo "Test finished but failed"
+                exit 1
+                ;;
+              *)
+                echo "Unknown status"
+                exit 1
+              esac
+            sleep 10
+          done
